name: ACR to Azure Web App
description: Deploy a container image to Azure Web App

inputs:
  subscription-id:
    description: 'Azure subscription ID'
    required: true
  resource-group:
    description: 'Azure resource group'
    required: true
  image-name:
    description: 'Name of the image to deploy'
    required: true
  registry-name:
    description: 'Name of the Azure Container Registry'
    required: true
  image-tag:
    description: 'Tag of the image to deploy'
    required: true
  credentials:
    description: 'Azure credentials'
    required: true
  web-app-name:
    description: 'Name of the Azure Web App'
    required: true

outputs:
  host-url:
    description: 'App Service Application URL'
    value: ${{ steps.webapps-deploy.outputs.webapp-url }}

runs:
  using: 'composite'

  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.credentials }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      id: webapps-deploy
      with:
        app-name: ${{inputs.web-app-name}}
        images: ${{ inputs.registry-name }}.azurecr.io/${{inputs.image-name}}:${{ inputs.image-tag }}
