name: ACR to Azure Web App
description: Deploy a container image to Azure Web App

inputs:
  subscription-id:
    description: 'Azure subscription ID'
    required: true
  resource-group:
    description: 'Azure resource group'
    required: true
  image-name:
    description: 'Name of the image to deploy'
    required: true
  registry-name:
    description: 'Name of the Azure Container Registry'
    required: true
  image-tag:
    description: 'Tag of the image to deploy'
    required: true
  credentials:
    description: 'Azure credentials'
    required: true
  acr-username:
    description: 'Azure Container Registry username'
    required: true
  acr-password:
    description: 'Azure Container Registry password'
    required: true

runs:
  using: 'composite'

  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.credentials }}

    - name: Deploy to Azure Web App
      run: az webapp config container set --name aclappconfig \
        --resource-group ${{inputs.resource-group}} \
        --container-image-name ${{ inputs.registry-name }}.azurecr.io/${{inputs.image-name}}:${{ inputs.image-tag }} \
        --container-registry-server-url https://aclacr.azurecr.io \
        --subscription ${{ inputs.subscription-id }}
        --container-registry-password ${{ inputs.acr-password }}
        --container-registry-username ${{ inputs.acr-username }}
