name: ACL ACR web

on:
  workflow_dispatch:

env:
  ACR_REGISTRY: 'aclacr'
  IMAGE_NAME: 'aclweb'
  DOCKERFILE_PATH: 'src/web/Dockerfile'
  AZURE_RESOURCE_GROUP: '1-1899c343-playground-sandbox'
  SCOURCE_ROOT_PATH: 'src/web'
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push image to ACR
        uses: ./.github/workflows/composite/build
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          image-name: ${{ env.IMAGE_NAME }}
          registry-name: ${{ env.ACR_REGISTRY }}
          image-tag: ${{ github.run_number }}
          dockerfile-path: ${{ env.DOCKERFILE_PATH }}
          source-root-path: ${{ env.SCOURCE_ROOT_PATH }}
          credentials: ${{ env.AZURE_CREDENTIALS }}
