name: 2. Build ACL web (ACR)

on:
  workflow_dispatch:

env:
  ACR_REGISTRY: ${{ vars.ACR_REGISTRY }}
  IMAGE_NAME: ${{ vars.WEB_APP_IMAGE_NAME }}
  DOCKERFILE_PATH: 'src/web/Dockerfile'
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  SCOURCE_ROOT_PATH: 'src/web'
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push image to ACR
        uses: ./.github/workflows/composite/build
        with:
          image-name: ${{ env.IMAGE_NAME }}
          registry-name: ${{ env.ACR_REGISTRY }}
          image-tag: ${{ github.run_number }}
          dockerfile-path: ${{ env.DOCKERFILE_PATH }}
          source-root-path: ${{ env.SCOURCE_ROOT_PATH }}
          credentials: ${{ env.AZURE_CREDENTIALS }}
