name: 3. Deploy ACL web (AWA)

on:
  push:
    branches: [$default-branch]
    paths:
      - 'src/web/**'
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ACR_REGISTRY: ${{ vars.ACR_REGISTRY }}
  ACR_IMAGE_NAME: ${{ vars.WEB_APP_IMAGE_NAME }}
  ACR_USERNAME: ${{ vars.ACR_USERNAME}}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: ./.github/workflows/composite/deploy
        with:
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          image-name: ${{ env.ACR_IMAGE_NAME }}
          registry-name: ${{ env.ACR_REGISTRY }}
          image-tag: ${{ github.run_number }}
          credentials: ${{ env.AZURE_CREDENTIALS }}
          acr-username: ${{ env.ACR_USERNAME }}
          acr-password: ${{ env.ACR_PASSWORD }}
