name: 3. Deploy ACL web (AWA)

on:
  workflow_dispatch:

env:
  ACR_REGISTRY: ${{ vars.ACR_REGISTRY }}
  IMAGE_NAME: ${{ vars.WEB_APP_IMAGE_NAME }}
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  ACR_USERNAME: ${{ vars.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

jobs:
  build:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy image to AWA
        uses: ./.github/workflows/composite/deploy
        with:
          image-name: ${{ env.IMAGE_NAME }}
          registry-name: ${{ env.ACR_REGISTRY }}
          image-tag: ${{ github.run_number }}
          credentials: ${{ env.AZURE_CREDENTIALS }}
          acr-username: ${{ env.ACR_USERNAME }}
          acr-password: ${{ env.ACR_PASSWORD }}
