name: 3. Deploy ACL web (AWA)

on:
  push:
    branches: [$default-branch]
    paths:
      - 'src/web/**'
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
  AZURE_CREDENTIALS: '{ clientId: "${{ secrets.AZURE_CLIENT_ID }}", clientSecret: "${{ secrets.AZURE_CLIENT_SECRET }}", subscriptionId: "${{ secrets.AZURE_SUBSCRIPTION_ID }}", tenantId: "${{ secrets.AZURE_TENANT_ID }}" }'
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ACR_NAME: ${{ vars.ACR_NAME }}
  ACR_IMAGE_NAME: ${{ vars.ACR_IMAGE_NAME }}
  WEB_APP_NAME: ${{ vars.WEB_APP_NAME }}

jobs:
  deploy:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure Web App
        uses: ./.github/workflows/composite/deploy
        with:
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}
          resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
          image-name: ${{ env.ACR_IMAGE_NAME }}
          registry-name: ${{ env.ACR_NAME }}
          image-tag: 'latest'
          credentials: ${{ env.AZURE_CREDENTIALS }}
          web-app-name: ${{ env.WEB_APP_NAME }}
